apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lqkwt0n09-python
  janus-idp.io/tekton: lqkwt0n09-python
  backstage.io/kubernetes-id: lqkwt0n09-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lqkwt0n09-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
