apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lqkwt0n09-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lqkwt0n09-python 
  name: lqkwt0n09-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lqkwt0n09-python 
